% Generates a horizontal and vertical offset for the space where a new cell
% is concieved. row, col is the location of the original cell and width is
% the width of the cell array, used for 'wrapping' the grid so a cell at
% the edge of the grid splitting towards the space beyond it will wrap
% around to the otherside. Direction randomly generated by randi(3) where
% 1=left, 2=down, 3=right.
function [offset_h, offset_v, row, col] = newcelldirection(row, col, width)
    offset_h = 0;
    offset_v = 0;
    switch randi(3)
        case 1
            if col == 1
                col = width+1;
            end
            offset_h = -1;
        case 2
            if row ~= 1
                offset_v = -1;
            end
        otherwise
            if col == width
                col = 0;
            end
            offset_h = 1;
    end
end